# Generated by Django 4.1.7 on 2023-03-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='ano_primeiro_lancamento',
            field=models.IntegerField(default=float),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='foto_perfil',
            field=models.ImageField(default=0.0, upload_to='artistas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='qtd_musicas_lancadas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='tipo',
            field=models.CharField(default='builtins', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=50)),
                ('tempo_duracao', models.FloatField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musicas', to='artista.artista')),
            ],
        ),
    ]
