# Generated by Django 4.1.7 on 2023-03-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0003_alter_artista_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artista.artista'),
        ),
    ]
