# Generated by Django 4.1.7 on 2023-03-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0004_alter_musica_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='qtd_musicas_lancadas',
            new_name='quantidade_de_musicas_lançadas',
        ),
    ]
