# Generated by Django 4.1.7 on 2023-03-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0005_rename_qtd_musicas_lancadas_artista_quantidade_de_musicas_lançadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='ano_primeiro_lancamento',
            new_name='ano_do_primeiro_lançamento',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='foto_perfil',
            new_name='foto_de_perfil',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='quantidade_de_musicas_lançadas',
            new_name='quantidade_de_músicas_lançadas',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='tipo',
            new_name='tipo_de_música',
        ),
    ]
