# Generated by Django 4.1.7 on 2023-03-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0006_rename_ano_primeiro_lancamento_artista_ano_do_primeiro_lançamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='tipo_de_música',
            field=models.CharField(choices=[('B', 'Banda'), ('C', 'Coral'), ('S', 'Solo')], default='S', max_length=30),
        ),
    ]
