# Generated by Django 4.1.7 on 2023-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0008_alter_artista_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
    ]
