# Generated by Django 4.1.7 on 2023-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0009_alter_artista_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='tipo_de_música',
            field=models.CharField(choices=[('Banda', 'Banda'), ('Coral', 'Coral'), ('Solo', 'Solo')], default='Solo', max_length=30),
        ),
    ]
