# Generated by Django 4.1.7 on 2023-03-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0010_alter_artista_tipo_de_música'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='estilo',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Gospel', 'Gospel'), ('Pop', 'Pop')], default='Gospel', max_length=50),
        ),
    ]
