# Generated by Django 4.1.7 on 2023-03-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0011_alter_musica_estilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='foto_de_perfil',
            new_name='foto',
        ),
    ]
