# Generated by Django 4.1.7 on 2023-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0012_rename_foto_de_perfil_artista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='artistas/%Y%/%m/%d/'),
        ),
    ]
