# Generated by Django 4.1.7 on 2023-03-29 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0016_rename_nome_musica_nome_musica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='ano_do_primeiro_lançamento',
            new_name='ano_do_primeiro_lancamento',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='quantidade_de_músicas_lançadas',
            new_name='quantidade_de_músicas_lancadas',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='tipo_de_música',
            new_name='tipo_de_musica',
        ),
    ]
